"🌐 web":
  - any: ["apps/www/**/*"]

"📱 mobile":
  - any: ["apps/mobile/**/*"]

"💻 @kafeasist/api":
  - any: ["packages/@kafeasist:api/**/*"]

"💾 @kafeasist/db":
  - any: ["packages/@kafeasist:db/**/*"]

"👤 @kafeasist/auth":
  - any: ["packages/@kafeasist:auth/**/*"]
