packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.748
  "@trpc/react-query": ^11.0.0-rc.748
  "@trpc/server": ^11.0.0-rc.748
  "@types/node": ^22.10.7
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.7.2
  zod: ^3.23.8
  dotenv-cli: ^8.0.0

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  next:
    next: 15.1.6
  auth:
    better-auth: ^1.1.16
