packages:
  - "apps/www"
  - "apps/mobile"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.377
  "@trpc/react-query": ^11.0.0-rc.377
  "@trpc/server": ^11.0.0-rc.377
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
