name: CI

on:
    pull_request:
        branches: ['*']

jobs:
    lint:
        runs-on: ubuntu-latest

        name: Lint with ESLint
        steps:
            - name: Action start
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Check lint
              run: pnpm lint

            - name: Run Prettier for format check
              run: pnpm format

            - name: Check manypkg
              run: pnpm manypkg:check
