name: Publish

on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: "pnpm"

      - run: pnpm install
      - name: Create release
        id: create_release
        uses: changesets/action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: pnpm run build
          commit: "chore(release): update versioning and publish"
          title: "chore(release): update versioning and publish"
